wooga/atlas-unity

- README.md
- src/integrationTest/groovy/wooga/gradle/unity/GradleVersionSupportSpec.groovy
The `GradleVersionSupportSpec` will test basic plugin apply and `build`
tasks against a list of gradle versions.
Document supported versions in README
> Add gradle version support tests

- README.md
- src/integrationTest/groovy/wooga/gradle/unity/AssembleResourcesIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/GradleVersionSupportSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/PluginConfigurationSpec.groovy
- src/main/groovy/wooga/gradle/unity/AndroidResourceCopyMethod.groovy
- src/main/groovy/wooga/gradle/unity/DefaultUnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
- src/test/groovy/wooga/gradle/unity/UnityPluginSpec.groovy
This pull request brings in logic to define external dependencies for `iOS` and `Android`.
The plugin introduces a new phase at runtime. The lifecycle task `setup` will call `assembleResources`. This task will copy and unpack the dependencies provided in the `dependencies` block into the `Assets/Plugins` directory.
**example**
```
plugins {
id "net.wooga.unity" version "0.10.0"
}
dependencies {
android fileTree(dir: "libs", include: "*.jar")
android project(':android:SubProject')
ios fileTree(dir: "ios/classes")
ios project(':android:SubProject') //which bundles an .framework.zip
}
```
See more information in the changed `README.md`
> assemble external resources

- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
- src/main/groovy/wooga/gradle/unity/utils/NUnitReportNormalizer.groovy
- src/main/resources/schema/nunit_25_report.xslt
- src/main/resources/schema/nunit_30_report_partial.xslt
- src/test/groovy/wooga/gradle/unity/utils/NUnitReportNormalizerSpec.groovy
Versions of Unity >= 5.6 use NUnit 3. The generated reports from unity are missing the root node `test-run`. The normalizer will __try__ to do this after the tests have run.
> Add NUnit report normalizer

- src/main/groovy/wooga/gradle/unity/utils/ProjectSettings.groovy
- src/test/groovy/wooga/gradle/unity/utils/ProjectSettingsSpec.groovy
Unity has a slightly custom YAML format for all internal models. The
yaml parser can't read this out of the box. This pull request adresses
this issue by pre processing the file like described at
https://stackoverflow.com/a/27117480/1380824 …
> Fix ProjectSettings parser

- .gitignore
- src/integrationTest/groovy/wooga/gradle/unity/PluginConfigurationSpec.groovy
- src/main/groovy/wooga/gradle/unity/DefaultUnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
- src/test/groovy/wooga/gradle/unity/DefaultUnityPluginExtensionSpec.groovy
- src/test/groovy/wooga/gradle/unity/UnityPluginSpec.groovy
A defined `defaultBuildTarget` will be applied to all Tasks of type `AbstractUnityTask` as `buildTarget` property
Example:
```
unity {
defaultBuildTarget = "android"
}
```
> Add default build target

- src/integrationTest/groovy/wooga/gradle/unity/PluginConfigurationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/DefaultBatchModeAction.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
We introduced 2 smaller issues with the last releases that will break integration tests. I did these changes already in #9 but will pull them out again. …
> fix fallback to default target

- src/integrationTest/groovy/wooga/gradle/unity/PluginConfigurationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/TestTaskExecutionSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityActivationIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/DefaultUnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginTestExtension.groovy
- src/test/groovy/wooga/gradle/unity/DefaultUnityPluginExtensionSpec.groovy
- src/test/groovy/wooga/gradle/unity/UnityPluginSpec.groovy
Generate Tasks on all combinations of `TestPlatforms` (eg `PlayMode`, `EditMode`) and `BuildTargets` (eg `ios`, `android` ...).
The `testEditMode` and `testPlayMode` have been converted to life cycle tasks. The new task tree might look like this:
*task dependencies with `testBuildTargets: ios, android`*
```
:check
\--- :test
+--- :testEditMode
|    +--- :testEditModeAndroid
|    \--- :testEditModeIos
\--- :testPlayMode
+--- :testPlayModeAndroid
\--- :testPlayModeIos
``` …
> Generate multiple tests by build targets

- src/integrationTest/groovy/wooga/gradle/unity/TestIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/utils/ProjectSettings.groovy
- src/test/groovy/wooga/gradle/unity/utils/ProjectSettingsSpec.groovy
Unity supports both formats for `.asset` files (text/binary). Currently, we are only able to parse text-based project settings files.
* Add unit test
* Add integration test
> Catch invalid/binary settings file content

- src/main/groovy/wooga/gradle/unity/DefaultUnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/ActivationSpec.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/BaseBatchModeSpec.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/BatchModeAction.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/BatchModeSpec.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/DefaultActivationAction.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/DefaultActivationActionFactory.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/DefaultBatchModeAction.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/DefaultBatchModeActionFactory.groovy
- src/main/groovy/wooga/gradle/unity/tasks/AbstractBatchModeTask.groovy
- src/main/groovy/wooga/gradle/unity/tasks/AbstractUnityTask.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Activate.groovy
- src/main/groovy/wooga/gradle/unity/tasks/ReturnLicense.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Unity.groovy
- src/main/groovy/wooga/gradle/unity/tasks/UnityPackage.groovy
- src/test/groovy/wooga/gradle/unity/batchMode/DefaultActivationActionSpec.groovy
In order to streamline our plugins structure, we want to make more use of convention mapping as described here: http://mrhaki.blogspot.de/2010/10/gradle-goodness-set-task-values-with.html 
* ![CHANGE] set values by convention mappings 
* ![CHANGE] Refactor Actions and Tasks …
> Use convention mapping for task properties

- src/integrationTest/groovy/wooga/gradle/unity/BaseBatchModeIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/PluginConfigurationSpec.groovy
- src/main/groovy/wooga/gradle/unity/DefaultUnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/BaseBatchModeSpec.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/DefaultBatchModeAction.groovy
- src/main/groovy/wooga/gradle/unity/tasks/AbstractUnityTask.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Activate.groovy
- src/main/groovy/wooga/gradle/unity/tasks/UnityPackage.groovy
- src/test/groovy/wooga/gradle/unity/DefaultUnityPluginExtensionSpec.groovy
The logs for each tasks are based on the taskname. It would be nice to add another level so you can invoke gradle multiple times with different parameters without overriding the logs and reports. This is mainly for a jenkins workflow.
The default should be `""`. There should be the 3 typical ways to set/override it.
* property in task
* property in extension
* gradle parameter `-P...=`
resolves #15 
* ![ADD] logCategory  …
> Add property logCategory

- src/integrationTest/groovy/wooga/gradle/unity/TestTaskExecutionSpec.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
Remove unused Test task features for unity <= 5.5. 
* ![Remove] property `filter`
* ![Remove] property `categories`
* ![Remove] property `teamcity`
* ![Remove] property `verbose`
[IOS]:http://resources.atlas.wooga.com/icons/icon_iOS.svg …
> Remove Unity 5.5 Test task features

- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/DefaultBatchModeAction.groovy
- src/main/groovy/wooga/gradle/unity/tasks/AbstractUnityTask.groovy
- src/test/groovy/wooga/gradle/unity/UnityPluginSpec.groovy
As discussed here #26 we want to make more use of convention mapping for default values.
* ![ADD] CM for `unityPath`
* ![ADD] CM for `projectPath `
* ![ADD] CM for `redirectStdOut `
[IOS]:http://resources.atlas.wooga.com/icons/icon_iOS.svg …
> Default values by convention mapping

- src/integrationTest/groovy/wooga/gradle/unity/BaseBatchModeIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
With the last changes we somehow brought in a regression for the
`logCategory` value. It seems we no longer evaluate clojure values at
one point. Since we try to limit API's with clojures that is Ok. I run
the tests and the one testing the `logCategory` also failed (strange).
So I changed the default mapping to the old `conventionMapping` style
and it works.
resolved #39  …
> Fix logCategory default value

- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
- src/test/groovy/wooga/gradle/unity/tasks/TestSpec.groovy
Unity released the first final version of unity `2018.1`. This change
enables the test task feature for all unity 2017 versions and the first
2018.1 release. …
> Activate test task feature for 2018.1

- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
- src/test/groovy/wooga/gradle/unity/tasks/TestSpec.groovy
This change enables the test task feature for all unity versions `5.5 < version < 2018`.
[ANDROID]:http://resources.atlas.wooga.com/icons/icon_android.svg "Android" …
> Activate test task feature for unity <= 2018

- src/integrationTest/groovy/wooga/gradle/unity/BaseBatchModeIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/internal/DefaultUnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/utils/internal/UnityHub.groovy
- src/test/groovy/wooga/gradle/unity/DefaultUnityPluginExtensionSpec.groovy
- src/test/groovy/wooga/gradle/unity/utils/internal/UnityHubSpec.groovy
This patch adds support to fetch the __default__ unity editor installation through [Unity Hub]. The order for fetching the __default__ location is as follows:
1. configured `path` in `build.gradle`
2. configured `path` in `gradle.properties`
3. configured `path` in `env`
4. prefered version configured in [Unity Hub] (if available)
5. default system installation location
All logic for [Unity Hub] is contained on a single utility class `UnityHub`. This patch and the posibility to lookup editor version installations through [Unity Hub] is the basis for a future feature to fetch the matching unity version based on the project editor version.
[Unity Hub]:	https://docs.unity3d.com/Manual/GettingStartedUnityHub.html …
> Add unity hub support

- src/integrationTest/groovy/wooga/gradle/unity/UnityActivationIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/internal/DefaultActivationAction.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Activate.groovy
- src/main/groovy/wooga/gradle/unity/tasks/ReturnLicense.groovy
- src/main/groovy/wooga/gradle/unity/tasks/internal/AbstractUnityActivationTask.groovy
It turns out the unity activation routine will open and import a project. Since we don't provide a project path for the `activate` and `returnLicense` tasks this can lead to build errors because Unity will pick the last project opened on the system. This picked project could be incompatible and fail the activation task.
This is a very simple patch to provide the project path to `activate` and `returnLicense` tasks. The whole structure should be cleaned up in another change. The separation of  AbstractUnityProjectTask` and `AbstractUnityActivationTask` makes no real sense anymore.
* ![FIX] ![UNITY] activation task
[UNITY]:https://atlas-resources.wooga.com/icons/icon_unity.svg "Unity" …
> Fix unity activation

- Jenkinsfile
- build.gradle
- src/integrationTest/groovy/wooga/gradle/unity/IntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityIntegrationRealSpec.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/internal/UnityLogErrorReader.groovy
Instead of using a unityversion being installed on the test system this patch ensures a unity installation at test runtime. It uses a spock extension library [spock-unity-version-manager-extension]. Tests some tests for windows are disabled because there is an issue with
installing unity without admin rights.
* ![IMPROVE] bootstrap preinstalled Unity versions in tests
[spock-unity-version-manager-extension]: https://github.com/wooga/spock-unity-version-manager-extension …
> Bootstrap preinstalled Unity version in tests

- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
Unity `5.6` added a complete new test runner compared to the one used in `5.5`. The main problem was a bug in unity. When the tests where executed in _batchmode_ unity actually never executed anything. This was true also in `2017` versions of unity. We tested this with `2018` and it looks like the issue was fixed. I enable _batchmode_ for all versions >= 2018.
* ![IMPROVE] enable _batchmode_ for tests in unity >= 2018 …
> Enable batchmode for tests in Unity >= 2018

- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
Not sure if we need this check at all. Or if we should already set it to 2021?
* ![IMPROVE] Add test support for Unity 2020 …
> Add test support for Unity 2020

- src/integrationTest/groovy/wooga/gradle/unity/TestTaskExecutionSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginConsts.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginConvention.groovy
- src/main/groovy/wooga/gradle/unity/batchMode/internal/DefaultBatchModeAction.groovy
- src/main/groovy/wooga/gradle/unity/internal/DefaultUnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
For years batchmode for edit and playmode tests was set to `true` due to some issues with Unity when not running them with a full Editor. We changed that to hardcode default to a `true` value when the editor version used is newer than 2018.
Some teams would like to configure the plugin to run edit/playmode tests without batchmode flag for some setups. This patch adds additional properties for the plugin extension to easily set this for a range of generated tasks.
```groove
unity {
batchModeForEditModeTest = true
batchModeForPlayModeTest = false
}
```
This extension variables can be set also via environment/gradle properties
`unity.batchModeForEditModeTest`
`UNITY_BATCH_MODE_FOR_EDIT_MODE_TEST=YES`
`unity.batchModeForPlayModeTest`
`UNITY_BATCH_MODE_FOR_PLAY_MODE_TEST=YES`
* ![IMPROVE] …
> Allow batchmode configuration for Test task

- src/integrationTest/groovy/wooga/gradle/unity/TestTaskExecutionSpec.groovy
- src/main/groovy/wooga/gradle/unity/internal/DefaultUnityPluginExtension.groovy
The last patch added properties to override the batchmode flag for edit/playmode tests. The default value when no values is provided was set to false which breaks for some builds. This patch sets the default value back to `true` by default.
* ![FIX] default value for `batchmode` flag in edit/playmode test …
> Fix default value for batchmode for test task

- src/integrationTest/groovy/wooga/gradle/unity/TestTaskExecutionSpec.groovy
- src/main/groovy/wooga/gradle/unity/internal/DefaultUnityPluginExtension.groovy
I made a small error in the getter implemention for both `getBatchModeForEditModeTest` and `getBatchModeForPlayModeTest` in the `DefaultUnityPluginExtension` class. I used a `Boolean` class to make sure that the default value would be `null` not `false`. My problem was that the `if` check I provided also checks if the value is `false`. In this case the body was not executed and the default value was being calculated from properties/environment which falls back to `true`. I want to return the value present in the to be checked `Boolean` field if it is not `null` so I made the check more explicit.
* ![FIX] `getBatchModeForEditModeTest` implementation
* ![FIX] `getBatchModeForPlayModeTest` implementation …
> Fix getBatchModeForEditModeTest and getBatchModeForPlayModeTest in extension

- src/integrationTest/groovy/wooga/gradle/unity/IntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/SetAPICompLevelIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/APICompatibilityLevel.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginConsts.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginConvention.groovy
- src/main/groovy/wooga/gradle/unity/internal/DefaultUnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/tasks/SetAPICompatibilityLevel.groovy
- src/test/groovy/wooga/gradle/unity/APICompatibilityLevelSpec.groovy
- src/test/groovy/wooga/gradle/unity/DefaultUnityPluginExtensionSpec.groovy
- src/test/groovy/wooga/gradle/unity/utils/internal/ProjectSettingsSpec.groovy
Adds a new task to set the API compatibility level on the ProjectSettings.asset, which will be used to test Unity versions against different NET runtimes (2, 4.6)
* ![ADD] SetAPICompatibilityLevel
* ![ADD] APICompatibilityLevel
* ![UPDATE] DefaultUnityPluginExtension, UnityPlugin
* ![UPDATE] UnityPluginConsts, UnityPluginConvention …
> Add API compatibility level task

- Jenkinsfile
- src/integrationTest/groovy/wooga/gradle/unity/SetAPICompLevelIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/APICompatibilityLevel.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/tasks/SetAPICompatibilityLevel.groovy
- src/main/groovy/wooga/gradle/unity/utils/GenericUnityAsset.groovy
- src/main/groovy/wooga/gradle/unity/utils/internal/ProjectSettings.groovy
- src/main/groovy/wooga/gradle/unity/utils/internal/UnityAssetFile.groovy
- src/main/groovy/wooga/gradle/unity/utils/internal/UnityVersionManager.groovy
- src/test/groovy/wooga/gradle/unity/APICompatibilityLevelSpec.groovy
- src/test/groovy/wooga/gradle/unity/utils/internal/ProjectSettingsSpec.groovy
- src/test/groovy/wooga/gradle/unity/utils/internal/UnityAssetFileSpec.groovy
Fixes the API compatibility level set task, which was setting a deprecated property instead of the newer one (of type Map).
Tests:
**NET STANDARD 2**
**NET 4**
* ![UPDATE] UnityAssetFile
* ![UPDATE] ProjectSettings
* ![UPDATE] SetAPICompatibilityLevel
[REMOVE]:http://resources.atlas.wooga.com/icons/icon_remove.sv …
> Fix SetAPICompatibilityLevel task

- src/integrationTest/groovy/wooga/gradle/unity/SetAPICompLevelIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/APICompatibilityLevel.groovy
- src/main/groovy/wooga/gradle/unity/tasks/SetAPICompatibilityLevel.groovy
- src/test/groovy/wooga/gradle/unity/APICompatibilityLevelSpec.groovy
- src/test/groovy/wooga/gradle/unity/DefaultUnityPluginExtensionSpec.groovy
- src/test/groovy/wooga/gradle/unity/utils/internal/ProjectSettingsSpec.groovy
Several of the APICompatiblityLevel values had a missing _ after _net_. This corrects it.
https://docs.unity3d.com/ScriptReference/ApiCompatibilityLevel.html
Downstream projects that use this will need to be updated accordingly, though not urgently as there's a fallback mechanism in place for the parsing to map the incorrect values to the correct ones.
* ![FIX] APICompatibilityLevel enum values for net_2_0, net_2_0_subset, net_4_6. …
> Fixes missing _ for several APICompatibilityLevel values

- src/main/groovy/wooga/gradle/unity/tasks/SetAPICompatibilityLevel.groovy
If the project settings file is not set, an exception is thrown due to it trying to access it. We should instead skip when it's not found.
> Skip SetAPICompLevel task if the project settings file is not present

- src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/models/BuildTarget.groovy
The old plugin version only allowed to set the BuildTarget flag with an enum. To check if a value is provided, the enum contained a value `undefined` so the task impl could check if the flag is actually provided. This is no longer needed and adds a small bug when the flag is not set. I removed the enum value and all mentions in code and adjusted the tests.
* ![FIX] remove default `BuildTarget.undefined` …
> Fix remove default BuildTarget.undefined

- build.gradle
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginConventions.groovy
- src/main/groovy/wooga/gradle/unity/utils/PlatformUtils.groovy
The current check fails on the CI for Linux since there's no license directory (it was returning null)
* ![UPDATE] UnityPLuginConventions …
> Fix license directory Linux check

- src/integrationTest/groovy/wooga/gradle/unity/UnityIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityTask.groovy
- src/main/groovy/wooga/gradle/unity/traits/ArgumentsSpec.groovy
Add a property for setting the environment for an Unity Task.
* ![UPDATE] UnityTask
* ![UPDATE] ArgumentsSpec
[ANDROID]:http://resources.atlas.wooga.com/icons/icon_android.svg …
> Unity Task environment setter

- src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityTask.groovy
The ArgumentsSpec.environment in UnityTask was not being constructed to the correct mapProperty type.
* ![FIX] UnityTask …
> Fix the environment initialization in UnityTask

- src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
This patch sets the default environment used to call Unity to `System.env`. It is possible to append values to this default env or reset it completely.
Unity needs the `HOME` variable by default and maybe some more.
* ![FIX] default environment for Unity invocation …
> Fix default environment for Unity invocation

- src/integrationTest/groovy/wooga/gradle/IntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/utils/PropertyQueryTaskWriter.groovy
- src/integrationTest/groovy/wooga/gradle/utils/PropertyUtils.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Activate.groovy
Rewrites how the values of properties are queried by the integration tests by using a _writer_ object which handles the writing of the query task and provides the functions for testing them.
The newer API simplifies the writing of these property tests:
```groovy
when:
def query = new PropertyQueryTaskWriter("${extensionName}.${property}")
query.write(buildFile)
def result = runTasksSuccessfully(query.taskName)
then:
query.matches(result, testValue)
```
* ![UPDATE] UnityIntegrationTest
* ![IMPROVE] *IntegrationTests
* ![ADD] PropertyQueryTaskWriter …
> Refactor how the values of properties in integration tests are queried

- src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/tasks/GenerateSolutionTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/tasks/GenerateSolution.groovy
Created new generateSolution task that generates a solution file (if it doesn't exists) by executing Unity's `UnityEditor.SyncVS.SyncSolution` method. Its a pretty simple operation, with no parameters needed so there are no properties associated to this task.
* ![ADD] new generateSolution task …
> Add new generate solution task

- src/integrationTest/groovy/wooga/gradle/IntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginConventions.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnityBaseSpec.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnitySpec.groovy
- src/main/groovy/wooga/gradle/unity/utils/UnityFileTree.groovy
- src/test/groovy/wooga/gradle/unity/utils/UnityFileTreeTest.groovy
Created properties for key executables/folders inside unity folder structure. As unity folder structure differs by OS, we try first to find the root folder by name, and if this fails, we just go up the file tree a bunch of times hoping to hit the right directory. Then, from this root directory, we try to find the dotnet executable and mono framework folder. All of these can be overwritten by user by informing them explicitly on the extension.
All of these file tree-related operations are on the UnityFileTree class.
* ![ADD] Added unityRoot property to extension
* ![ADD] Added unityDotnet property to extension
* ![ADD] Added unityMonoFramework property to extension
[ADD]:http://resources.atlas.wooga.com/icons/icon_add.svg …
> Added unity root, unity dotnet and unity mono framework properties

- src/integrationTest/groovy/wooga/gradle/unity/tasks/TestTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
Turning on CodeCoverage reporting on Unity 2019 project
```groovy
unity {
enableTestCodeCoverage = true
}
```
adds most code coverage parameters except `-enableCodeCoverage`.
resolves #117
* ![FIX] version number comparison for enableCodeCoverage argument in the `Test` task . …
> FIx: Coverage version floor comparison

- src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/utils/PropertyQueryTaskWriter.groovy
- src/integrationTest/groovy/wooga/gradle/utils/PropertyUtils.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnityCommandLineSpec.groovy
Add missing getters for Unity task command line options, and a generated test that will catch if any newer ones don't have them implemented.
* ![UPDATE] UnityCommandLineSpec …
> Add missing getters for unity task command line options

- src/main/groovy/wooga/gradle/unity/utils/PropertyLookup.groovy
The patch [#110] removed the class `wooga.gradle.unity.utils.PropertyLookup` in favor of `com.wooga.gradle.PropertyLookup` from the new library `com.wooga.gradle:gradle-commons`. This introduced a breaking API change as some downstream projects are using the utility class from this package. I added the class back but instead of adding a copy Iextended the new util from `gradle-commons`. I marked this class as deprecated to discurage the further usage.
* ![FIX] revert `PropertyLookup` API with a standin class …
> Fix removed PropertyLookup API

- src/main/groovy/wooga/gradle/unity/traits/UnitySpec.groovy
The newer UnitySpec properties were missing @Internal annotations.
* ![UPDATE] UnitySpec
[ANDROID]:http://resources.atlas.wooga.com/icons/icon_android.svg "Android" …
> Add missing internal annotations

- src/integrationTest/groovy/wooga/gradle/unity/UnityIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/utils/PropertyQueryTaskWriter.groovy
- src/main/groovy/wooga/gradle/unity/UnityTask.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnityCommandLineSpec.groovy
When loggin both to stdout and to a file the parameter for the `-logFile` flag must be set to `-` 
not the filepath. The internal logic will read the stdout and both print it to stdout and 
to the provided file.
resolves #120 
* ![FIX] UnityTask: -logFile being set when logToStdout was true …
> Fix logToStdout when logPath is also set

- build.gradle
The 0. version range should never be declared with a range since any new minor release can contain breaking changes. We need to pin to a compatible version and update manually or through use of dependabot.
* ![FIX] pin unstable version of `com.wooga.gradle:gradle-commons` …
> Pin version of com.wooga.gradle:gradle-commons [ATLAS-268]

- src/integrationTest/groovy/wooga/gradle/unity/tasks/TestTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
During PP UBS integration we noticed that their build executes EditMode tests twice and ignores the PlayMode tests.
There was a typo introduced in 2.x.
* ![FIX] PlayMode test tasks are executed as EditMode …
> Fix PlayMode test tasks are executed as EditMode

- build.gradle
- src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/tasks/AddUPMPackagesTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/testutils/GradleRunResult.groovy
- src/integrationTest/groovy/wooga/gradle/utils/PropertyQueryTaskWriter.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/tasks/AddUPMPackages.groovy
- src/main/groovy/wooga/gradle/unity/tasks/GenerateSolution.groovy
- src/test/groovy/wooga/gradle/unity/UnityPluginTest.groovy
Added task for installing UPM packages, as well as interlinking it with the test task (as these packages may be necessary to build the project and run tests). Work here was done partially by me (Joaquim) and another part by Sebu. Packages for this task can be put into the task itself, or using the `upmPackages` extension property.
Some relevant test changes were needed as the old tests would pick up logs from all tasks that were being ran, not just from the task being tested. Usage right now is more akin to this, as `upmPackages` is a gradle `PropertyMap`.
```gradle
unity {
upmPackages.with {
put("package", "version")
}
}
```
or
```gradle
unity {
upmPackages.put("package", "version")
}
```
* ![ADD] `AddUPMPackages` task …
> Add basic UPM package install logic

- build.gradle
- src/integrationTest/groovy/wooga/gradle/unity/tasks/TestTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/internal/InputFileTreeFactory.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnityTestSpec.groovy
Unity Test task inputs weren't taking as input anything related to the project file structure, so it ended up being up-to-date even when there were relevant changes to the project. the `inputFiles` Input was create on the task  in order to resolve this. 
* ![FIX] Test task being up-to-date in wrong situations …
> Test task up-to-date fix

- build.gradle
- src/integrationTest/groovy/wooga/gradle/unity/tasks/GenerateSolutionTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/tasks/TestTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/internal/InputFileTreeFactory.groovy
- src/main/groovy/wooga/gradle/unity/tasks/GenerateSolution.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnityTestSpec.groovy
GenerateSolution task was being up-to-date even though it has no inputs and it wasn't meant to be. This happens because of inherited inputs from its parent class.
Ps: this PR is forked from #137 
* ![FIX] GenerateSolution now is never up-to-date
[REMOVE]:http://resources.atlas.wooga.com/icons/icon_remove.svg …
> Generate solution task up-to-date fix

- Jenkinsfile
- build.gradle
- settings.gradle
This patch adds snyk monitoring to the build pipeline. It will hook itself into the check and publish stages.
The patch also sets a dependency helper plugin net.wooga.cve-dependency-resolution which applies overrides for dependencies with know fixes for security issues.
* ![ADD] `snyk` monitoring
* ![ADD] `net.wooga.snyk-wdk-java` snyk convention plugin
* ![ADD] `net.wogoa.cve-dependency-resolution` plugin …
> Add snyk monitoring

- .github/PULL_REQUEST_TEMPLATE.md
- Jenkinsfile
- build.gradle
Because of security issues reported for the coveralls gradle plugin I decided to remove the feature during build. It is not enough to just stop sending reports via jenkins. We also need to update to `net.wooga.plugins` > `4.0.0` because this version removes the dependency.
I remove the coveralls token in the Jenkinsfile so our base pipeline won't try to call the coveralls task on the gradle project.
* ![UPDATE] `net.wooga.plugins` to version `4.0.0` to remove coveralls dependency
* ![REMOVE] coveralls token in Jenkinsfile
[CHANGE]: …
> Remove coveralls reporting [ATLAS-762]

- src/integrationTest/groovy/wooga/gradle/unity/tasks/GenerateUpmPackageTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/tasks/GenerateUpmPackage.groovy
Fixes the predicate for package directory on the generate upm package task.
* ![FIX] Fixes the predicate for package directory on the generate upm package task.
[IOS]: …
> Fix predicate for package directory on generate UPM package task

- src/integrationTest/groovy/wooga/gradle/unity/tasks/DefaultUnityTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/models/UnityCommandLineOption.groovy
- src/main/groovy/wooga/gradle/unity/tasks/Activate.groovy
- src/main/groovy/wooga/gradle/unity/tasks/AddUPMPackages.groovy
- src/main/groovy/wooga/gradle/unity/tasks/ReturnLicense.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnityCommandLineSpec.groovy
Fix the cache server upload/download options not being disabled.
* ![UPDATE] `UnityCommandLineOption`
[IOS]:      https://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]: …
> Fix the cache server upload/download options

- src/main/groovy/wooga/gradle/unity/models/UnityCommandLineOption.groovy
The cache server flag had an extra -.
* ![ADD] `UnityCommandLineOptions'
[IOS]:      https://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]: …
> Fix the cache server enable upload flag, which had an extra -

- .gitignore
- src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginConventions.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
Adds a convention for the `autoActivate` property (previously named `autoActivateUnity`), so that local developers need not have their license revoked!
* ![ADD] Conventions setup for `autoActivate`
* ![ADD] ignore `bin` directory
[REMOVE]: …
> Add a convention for the autoActivate property, deprecate the older name

- build.gradle
- src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/tasks/AddUPMPackagesTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/tasks/CreateProjectTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/tasks/ProjectManifestTaskSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/tasks/SetResolutionStrategyTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginConventions.groovy
- src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
- src/main/groovy/wooga/gradle/unity/UnityTask.groovy
- src/main/groovy/wooga/gradle/unity/models/ResolutionStrategy.groovy
- src/main/groovy/wooga/gradle/unity/models/UnityProjectManifest.groovy
- src/main/groovy/wooga/gradle/unity/tasks/AddUPMPackages.groovy
- src/main/groovy/wooga/gradle/unity/tasks/ProjectManifestTask.groovy
- src/main/groovy/wooga/gradle/unity/tasks/SetResolutionStrategy.groovy
- src/main/groovy/wooga/gradle/unity/traits/AddUnityPackagesSpec.groovy
- src/main/groovy/wooga/gradle/unity/traits/ResolutionStrategySpec.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnityPackageSpec.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnitySpec.groovy
- src/test/groovy/wooga/gradle/unity/UnityPluginTest.groovy
Adds task to modify the project package resolution strategy, `setResolutionStrategy`, according to this:
(https://docs.unity3d.com/Manual/upm-manifestPrj.html#resolutionStrategy)
The task class derives from a base `ProjectManifestTask`, which is now shared with the existing `AddUpmPackages` task that was previously implemented. 
* ![ADD] `setResolutionStrategy` plugin task
* ![IMPROVE] `AddUPMPackages` task base layout into a base task, `ProjectManifestTask`
[FIX]: …
> Add task to set the project package resolution strategy

- src/integrationTest/groovy/wooga/gradle/unity/tasks/GenerateUpmPackageTaskIntegrationSpec.groovy
- src/integrationTest/groovy/wooga/gradle/unity/testutils/SetupProjectLayoutTestTask.groovy
- src/main/groovy/wooga/gradle/unity/tasks/GenerateUpmPackage.groovy
- src/main/groovy/wooga/gradle/unity/traits/UnityPackageSpec.groovy
- src/main/groovy/wooga/gradle/unity/utils/PackageManifestBuilder.groovy
The regex to execute value substition for the `package.json` file
assumes spaces around the properties.
I removed the whole line patching logic with a two step copy setup.
The task first copies the package.json to a temp directory in the build dir
and adjustst the content according to the set properties.
The main package copy spec will draw the content from two locations
1. the main package dir
2. the temp directory where only the adjusted package.json is located
During copy only the package.json file form the temp dir will be taken into account.
The solution at hand is sadly not the best to continue going forward. But I wanted a simple fix now and deal with a proper solution (parsing the whole json instead of doing line matching).
The changes are quite big because I wanted to implement …
> Fix space in upm package replacement [ATLAS-1206]

- src/integrationTest/groovy/wooga/gradle/unity/tasks/GenerateUpmPackageTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/tasks/GenerateUpmPackage.groovy
- src/main/groovy/wooga/gradle/unity/utils/PackageManifestBuilder.groovy
Dependencies were being cleared by the `GenerateUpmPackage` task due a missing merge.
* ![FIX] `GenerateUpmPackage` dependencies being cleared
[IOS]: …
> Fix GenerateUpmPackage clearing dependencies

- src/main/groovy/wooga/gradle/unity/tasks/GenerateUpmPackage.groovy
- src/main/groovy/wooga/gradle/unity/traits/GenerateUpmPackageSpec.groovy
Adds an interface for generating the upm package on the existing task. This is to expose closures on it without having to expose the whole `Task` API.
* ![ADD] `GenerateUpmPackageSpec`
[IOS]: …
> Adds an interface for generating the upm package

- build.gradle
- src/integrationTest/groovy/wooga/gradle/unity/testutils/SetupProjectLayoutTestTask.groovy
- src/main/groovy/wooga/gradle/unity/tasks/GenerateUpmPackage.groovy
https://woogagmbh.atlassian.net/browse/ATLAS-1334
Replace the tar packer. This is done because we want to support samples in WDKs. For this, we need to support folders with "~" inside the name.
Since Gradle7, there is no way to modify the filter at runtime.
* ![ADD] commons-compress reference
* ![CHANGE] Replace TAR packer with the commons-compress implementation
[UPDATE]: …
> Replace Tar packer [ATLAS-1334]

- src/integrationTest/groovy/wooga/gradle/unity/tasks/GenerateSolutionTaskIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/tasks/GenerateSolution.groovy
Current generateSolution fix leaves a file behind in the project, which polutes the git, and potentially may add an extra script to the game. As this script is present when the solution is generated, its added to the solution as well, which can generate issues when the added script is removed in the cleanup task. As we need the rider extension anyway, its a better solution to just call it directly to generate a solution. 
* ![IMPROVE] generateSolution doesn't need to inject a script anymore
* ![FIX] solutions generated with `generateSolution` task fails in dotnet builds …
> Simpler, better fix for the generateSolution issue [ATLAS-1772]

- Dockerfile
- src/main/groovy/wooga/gradle/unity/UnityTask.groovy
Fixes bug where plugin crashes if unity execution fails due to a missing variable
* ![FIX] Plugin crashes when unity return non-zero status
[IOS]: …
> FIx plugin crashing when Unity return non-zero

- Dockerfile
- Jenkinsfile
- build.gradle
- src/integrationTest/groovy/wooga/gradle/unity/tasks/ClearDanglingUnityFilesIntegrationSpec.groovy
- src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
- src/main/groovy/wooga/gradle/unity/tasks/ClearDanglingUnityFiles.groovy
Add new task `clearDanglingUnityFiles` which removes the `Temp` dir from a Unity workspace before unity runs, when no other unity processes are running on this workspace.  
It checks for the `Library/EditorInstance.json` file for potential open Unity instances. If it doesn't find any matching unity processes, or if the file is not there, it deletes the `Temp/` directory in the workspace. This usually happens when a unity run crashes or is force-exited.
Also pins artifactory sdk to 2.19.0, as 2.19.1 uses groovy 4, for some reason. 
* ![ADD] `clearDanglingUnityFiles` task
* ![CHANGE] pin `org.jfrog.artifactory.client:artifactory-java-client-services` dependency to `2.19.0`
* ![CHANGE] minimum Java version is now 11 …
> Add task to remove dangling unity files in workspace before run
